### ISSUE TITLE
Could not compile

### ISSUE THREAD

**Issue by csezoli21** [matt-h/mpd-pulse#1]
Lexical-core due to 27 previous errors.
Errors:  E0277,  E0308

**Comment by matt-h** [comment]
Thanks. It built fine with Rust 1.48.0 which was the last version I built my copy with.

It looks like one of the dependencies doesn't build with the new version of Rust.

I started trying to update dependencies to new versions but it looks like this will need some changes due to changes in the dependencies.

**Comment by matt-h** [comment]
Fixed in https://github.com/matt-h/mpd-pulse/pull/2
